# Generated by Django 6.0.5 on 2026-05-24 07:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Monitors",
            new_name="Monitor",
        ),
    ]
