# Generated by Django 5.2.2 on 2026-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitors", "0002_rename_monitors_monitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkresult",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
